// Generated by tools/gen_agency_metadata.py from agencies/registry.json --
// do not hand-edit. Re-run the script after any registry change to update.

#include "transit/agency_metadata.h"

#include <cstring>

namespace transit {

const AgencyMetadata kAgencyMetadata[] = {
  {"sta", "Spokane Transit Authority", "Spokane, WA, USA", "https://www.spokanetransit.com/", false, "", "https://www.spokanetransit.com/developers-terms-of-use/"},
};

const size_t kAgencyMetadataCount = sizeof(kAgencyMetadata) / sizeof(kAgencyMetadata[0]);

const AgencyMetadata* findAgencyMetadata(const char* id) {
  for (size_t i = 0; i < kAgencyMetadataCount; ++i) {
    if (strcmp(kAgencyMetadata[i].id, id) == 0) return &kAgencyMetadata[i];
  }
  return nullptr;
}

}  // namespace transit
