// Generated by tools/gen_sta_tables.py from STA's published static GTFS
// feed -- do not hand-edit. Re-run the script against a fresh feed to
// update (see that script's docstring for where to get one).

#include "transit/sta_route_table.h"

#include <cstring>

namespace transit {
namespace sta {

const RouteInfo kStaRoutes[] = {
  {"1", "1", 0x93328E, 0xFFFFFF},
  {"11", "11", 0x337D35, 0xFFFFFF},
  {"12", "12", 0x337D35, 0xFFFFFF},
  {"124", "124", 0xD9306E, 0xFFFFFF},
  {"14", "14", 0x3155A6, 0xFFFFFF},
  {"144", "144", 0xD9306E, 0xFFFFFF},
  {"173", "173", 0x4E6470, 0xFFFFFF},
  {"190", "190", 0x4E6470, 0xFFFFFF},
  {"20", "20", 0xD71635, 0xFFFFFF},
  {"21", "21", 0xD71635, 0xFFFFFF},
  {"22", "22", 0x3155A6, 0xFFFFFF},
  {"223", "223", 0xD9306E, 0xFFFFFF},
  {"23", "23", 0x3155A6, 0xFFFFFF},
  {"247", "247", 0xD9306E, 0xFFFFFF},
  {"25", "25", 0xD71635, 0xFFFFFF},
  {"27", "27", 0x3155A6, 0xFFFFFF},
  {"28", "28", 0xD71635, 0xFFFFFF},
  {"294", "294", 0xD9306E, 0xFFFFFF},
  {"31", "31", 0x3155A6, 0xFFFFFF},
  {"32", "32", 0x3155A6, 0xFFFFFF},
  {"33", "33", 0xD71635, 0xFFFFFF},
  {"34", "34", 0x3155A6, 0xFFFFFF},
  {"342", "342", 0x337D35, 0xFFFFFF},
  {"343", "343", 0x337D35, 0xFFFFFF},
  {"35", "35", 0x3155A6, 0xFFFFFF},
  {"36", "36", 0x3155A6, 0xFFFFFF},
  {"4", "4", 0xD71635, 0xFFFFFF},
  {"43", "43", 0x3155A6, 0xFFFFFF},
  {"45", "45", 0x3155A6, 0xFFFFFF},
  {"6", "6", 0x4E6470, 0xFFFFFF},
  {"61", "61", 0x3155A6, 0xFFFFFF},
  {"62", "62", 0x3155A6, 0xFFFFFF},
  {"63", "63", 0x3155A6, 0xFFFFFF},
  {"633", "633", 0xD9306E, 0xFFFFFF},
  {"65", "65", 0x3155A6, 0xFFFFFF},
  {"66", "66", 0x4E6470, 0xFFFFFF},
  {"661", "661", 0x4E6470, 0xFFFFFF},
  {"662", "662", 0x4E6470, 0xFFFFFF},
  {"663", "663", 0x4E6470, 0xFFFFFF},
  {"664", "664", 0x4E6470, 0xFFFFFF},
  {"68", "68", 0x3155A6, 0xFFFFFF},
  {"7", "7", 0x4E6470, 0xFFFFFF},
  {"722", "722", 0x4E6470, 0xFFFFFF},
  {"724", "724", 0x4E6470, 0xFFFFFF},
  {"771", "771", 0x4E6470, 0xFFFFFF},
  {"9", "9", 0xD71635, 0xFFFFFF},
  {"93", "93", 0x3155A6, 0xFFFFFF},
  {"94", "94", 0x3155A6, 0xFFFFFF},
  {"95", "95", 0x3155A6, 0xFFFFFF},
  {"96", "96", 0x3155A6, 0xFFFFFF},
  {"97", "97", 0x3155A6, 0xFFFFFF},
  {"98", "98", 0x3155A6, 0xFFFFFF},
};

const size_t kStaRouteCount = sizeof(kStaRoutes) / sizeof(kStaRoutes[0]);

const RouteInfo* lookupStaRoute(const char* routeId) {
  size_t lo = 0;
  size_t hi = kStaRouteCount;
  while (lo < hi) {
    size_t mid = lo + (hi - lo) / 2;
    int cmp = strcmp(kStaRoutes[mid].routeId, routeId);
    if (cmp == 0) return &kStaRoutes[mid];
    if (cmp < 0) {
      lo = mid + 1;
    } else {
      hi = mid;
    }
  }
  return nullptr;
}

}  // namespace sta
}  // namespace transit
