#pragma once

// Transit-Elnk-Firmware -- on-device metadata for every "supported" entry
// in agencies/registry.json (name, attribution, terms of use) -- lets the
// settings portal show a configured second-source agency's copyright/
// credit info without network access or an SD-card pack manifest (which
// doesn't exist yet -- see docs/AGENCY_REGISTRY.md).
// Generated by tools/gen_agency_metadata.py from agencies/registry.json --
// do not hand-edit. Re-run the script after any registry change to update.
//
// "requested" entries aren't included: there's nothing to show for an
// agency nobody has built the integration for yet.

#include <cstddef>

namespace transit {

struct AgencyMetadata {
  const char* id;               // agencies/registry.json's "id"
  const char* name;
  const char* region;
  const char* website;          // may be empty
  bool attributionRequired;
  const char* attributionText;  // empty unless attributionRequired
  const char* termsUrl;         // may be empty
};

// Sorted by id for readability -- lookup below is a linear scan (a handful
// of entries at most, checked only when the settings portal is up, not a
// hot path like sta_route_table.h's per-departure lookupStaRoute()).
extern const AgencyMetadata kAgencyMetadata[];
extern const size_t kAgencyMetadataCount;

// nullptr if id isn't a "supported" entry in the registry as of the last
// regeneration -- an unregistered id, or one still status="requested".
const AgencyMetadata* findAgencyMetadata(const char* id);

}  // namespace transit
