#pragma once

// Transit-Elnk-Firmware -- STA route metadata (rider-facing name and
// panel color), keyed by the same route_id a live GTFS-RT TripUpdate
// carries in its TripDescriptor -- see sta_feed_parser.h. GTFS-RT itself
// carries no naming/color data (that's static-GTFS-only), so this is baked
// in from STA's routes.txt rather than fetched at runtime.
// Generated by tools/gen_sta_tables.py from STA's published static GTFS
// feed -- do not hand-edit. Re-run the script against a fresh feed to
// update (see that script's docstring for where to get one).

#include <cstddef>
#include <cstdint>

namespace transit {
namespace sta {

struct RouteInfo {
  const char* routeId;    // matches TripDescriptor.route_id
  const char* shortName;  // rider-facing route number, e.g. "34"
  uint32_t color;         // 0xRRGGBB, routes.txt route_color
  uint32_t textColor;     // 0xRRGGBB, routes.txt route_text_color
};

// Sorted by routeId (numeric order) for lookupStaRoute()'s binary search.
extern const RouteInfo kStaRoutes[];
extern const size_t kStaRouteCount;

// nullptr if routeId isn't a route this table knows about (e.g. the feed
// added a route since this table was last regenerated) -- callers fall
// back to displaying the raw route_id in that case.
const RouteInfo* lookupStaRoute(const char* routeId);

}  // namespace sta
}  // namespace transit
