#pragma once

// Transit-Elnk-Firmware -- STA stop lookup, keyed by the numeric stop code
// printed on the physical stop sign (what ConfigStore::staStopCode() stores,
// entered during setup -- see setup_flow.h). Resolves that to the
// alphanumeric stop_id the GTFS-RT feed actually keys its
// stop_time_update entries on (see sta_feed_parser.h), plus a human-readable
// name to confirm the pick during setup. Neither the code->id mapping nor the
// name is carried in the live feed itself -- both are static-GTFS-only, so
// this is baked in from STA's stops.txt rather than fetched at runtime.
// Generated by tools/gen_sta_tables.py from STA's published static GTFS
// feed -- do not hand-edit. Re-run the script against a fresh feed to
// update (see that script's docstring for where to get one).

#include <cstddef>
#include <cstdint>

namespace transit {
namespace sta {

struct StopInfo {
  uint16_t stopCode;   // printed on the sign; ConfigStore::staStopCode()
  char stopId[9];      // GTFS-RT stop_time_update.stop_id (<=8 chars + NUL)
  const char* stopName;
};

// Sorted by stopCode for lookupStaStop()'s binary search.
extern const StopInfo kStaStops[];
extern const size_t kStaStopCount;

// nullptr if stopCode isn't in this table (a typo, or STA added a stop since
// this table was last regenerated) -- callers surface that as "stop not
// found" rather than silently fetching nothing.
const StopInfo* lookupStaStop(uint16_t stopCode);

}  // namespace sta
}  // namespace transit
