#!/usr/bin/env python3
"""Generates include/transit/agency_metadata.h + src/transit/agency_metadata.cpp
from agencies/registry.json.

The settings portal needs to show a configured second-source agency's
name/attribution/terms without network access or (not built yet -- see
docs/AGENCY_REGISTRY.md) an SD-card pack manifest. Compiling the registry's
"supported" entries straight into flash is the same move
tools/gen_sta_tables.py already makes for STA's own route/stop tables, just
for the registry's own metadata instead of GTFS data.

"requested" entries are skipped -- there's nothing to show for an agency
nobody has built the integration for yet.

Usage: tools/gen_agency_metadata.py [path-to-registry.json]
Re-run after any agencies/registry.json change; CI does not do this for you
(unlike tools/gen_sta_tables.py's own weekly job, this has no schedule --
a registry PR is a rare, reviewed event, not a moving feed).
"""

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_REGISTRY = REPO_ROOT / "agencies" / "registry.json"
HEADER_PATH = REPO_ROOT / "include" / "transit" / "agency_metadata.h"
CPP_PATH = REPO_ROOT / "src" / "transit" / "agency_metadata.cpp"


def c_string_literal(s: str) -> str:
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


HEADER_TEMPLATE = """#pragma once

// Transit-Elnk-Firmware -- on-device metadata for every "supported" entry
// in agencies/registry.json (name, attribution, terms of use) -- lets the
// settings portal show a configured second-source agency's copyright/
// credit info without network access or an SD-card pack manifest (which
// doesn't exist yet -- see docs/AGENCY_REGISTRY.md).
// Generated by tools/gen_agency_metadata.py from agencies/registry.json --
// do not hand-edit. Re-run the script after any registry change to update.
//
// "requested" entries aren't included: there's nothing to show for an
// agency nobody has built the integration for yet.

#include <cstddef>

namespace transit {

struct AgencyMetadata {
  const char* id;               // agencies/registry.json's "id"
  const char* name;
  const char* region;
  const char* website;          // may be empty
  bool attributionRequired;
  const char* attributionText;  // empty unless attributionRequired
  const char* termsUrl;         // may be empty
};

// Sorted by id for readability -- lookup below is a linear scan (a handful
// of entries at most, checked only when the settings portal is up, not a
// hot path like sta_route_table.h's per-departure lookupStaRoute()).
extern const AgencyMetadata kAgencyMetadata[];
extern const size_t kAgencyMetadataCount;

// nullptr if id isn't a "supported" entry in the registry as of the last
// regeneration -- an unregistered id, or one still status="requested".
const AgencyMetadata* findAgencyMetadata(const char* id);

}  // namespace transit
"""

CPP_HEADER = """// Generated by tools/gen_agency_metadata.py from agencies/registry.json --
// do not hand-edit. Re-run the script after any registry change to update.

#include "transit/agency_metadata.h"

#include <cstring>

namespace transit {

const AgencyMetadata kAgencyMetadata[] = {
"""

CPP_FOOTER = """};

const size_t kAgencyMetadataCount = sizeof(kAgencyMetadata) / sizeof(kAgencyMetadata[0]);

const AgencyMetadata* findAgencyMetadata(const char* id) {
  for (size_t i = 0; i < kAgencyMetadataCount; ++i) {
    if (strcmp(kAgencyMetadata[i].id, id) == 0) return &kAgencyMetadata[i];
  }
  return nullptr;
}

}  // namespace transit
"""


def main() -> int:
    registry_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_REGISTRY
    registry = json.loads(registry_path.read_text())

    supported = [a for a in registry["agencies"] if a.get("status") == "supported"]
    supported.sort(key=lambda a: a["id"])

    rows = []
    for a in supported:
        attribution_required = bool(a.get("attribution_required", False))
        rows.append(
            "  {%s, %s, %s, %s, %s, %s, %s},"
            % (
                c_string_literal(a["id"]),
                c_string_literal(a["name"]),
                c_string_literal(a["region"]),
                c_string_literal(a.get("website", "")),
                "true" if attribution_required else "false",
                c_string_literal(a.get("attribution_text", "")),
                c_string_literal(a.get("terms_url", "")),
            )
        )

    HEADER_PATH.write_text(HEADER_TEMPLATE)
    CPP_PATH.write_text(CPP_HEADER + "\n".join(rows) + ("\n" if rows else "") + CPP_FOOTER)

    print(f"wrote {HEADER_PATH.relative_to(REPO_ROOT)}")
    print(f"wrote {CPP_PATH.relative_to(REPO_ROOT)} ({len(supported)} supported agencies)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
