#!/usr/bin/env python3
"""Regenerate STA (Spokane Transit Authority) reference data for
Transit-Elnk-Firmware, from STA's published static GTFS feed:

  1. include/transit/sta_route_table.h(.cpp) and sta_stop_table.h(.cpp) --
     small tables baked into firmware flash, always available regardless of
     SD card state. Cover exactly two things the live GTFS-RT feed doesn't
     carry itself: route_id -> rider-facing route number/name/color
     (routes.txt), and the numeric stop code printed on a physical stop
     sign -> the alphanumeric internal stop_id the feed actually keys on
     plus a display name (stops.txt).
  2. sd_card_data/sta/{routes,stops,trips}.bin -- the fuller dataset, meant
     to be copied onto the board's SD card (see docs/STA_INTEGRATION.md),
     including stop lat/lon (for future nearby-stop search) and all of
     trips.txt (trip_id -> route_id/direction_id/headsign) -- trips.txt
     alone is ~8,400 rows/463KB, too large to justify baking into flash
     alongside the firmware image, but exactly what's needed to reliably
     group departures by direction (GTFS-RT's own direction_id proved
     unreliable on STA's live feed, see sta_feed_parser.h) and show a
     trip's real headsign instead of relying on the live feed always
     carrying trip_short_name. SD is optional and this data supplements,
     never replaces, the flash tables -- see sta_gtfs_binary.h/sta_sd_store.h
     for the on-device reader and its no-card/no-file fallback.

STA's own site (spokanetransit.com) sits behind Cloudflare bot protection
that blocks a plain HTTP client (including this device's firmware), so this
reads from the Mobility Database's public unauthenticated mirror instead:
https://storage.googleapis.com/storage/v1/b/mdb-latest/o?prefix=us-washington-spokane-transit-authority
Look up the current .zip object there (the generation/filename changes each
time Mobility Database re-crawls STA) and pass its download URL or a local
path to this script.

Usage:
    python3 tools/gen_sta_tables.py path/to/sta_gtfs.zip
    python3 tools/gen_sta_tables.py https://storage.googleapis.com/.../sta-gtfs-NNN.zip

Regenerate periodically (STA route/stop/trip changes are infrequent enough
that this doesn't need to run on every build). Commit the flash header/cpp
pairs like any other generated asset in this repo (see
include/transit/powered_by_transit_badge.h for the same pattern); the
sd_card_data/ output is meant to be copied onto a physical SD card, not
committed (regenerating it is cheap, and it doesn't affect what firmware
builds -- see sd_card_data/README.md, written once by this script).
"""

import csv
import io
import struct
import sys
import urllib.request
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INCLUDE_DIR = REPO_ROOT / "include" / "transit"
SRC_DIR = REPO_ROOT / "src" / "transit"
SD_DATA_DIR = REPO_ROOT / "sd_card_data" / "sta"

# sta_gtfs_binary.h's shared file format: a 16-byte header (magic, record
# count, record size, blob byte-offset) followed by that many fixed-size
# records sorted ascending by each record's first 4 bytes (a little-endian
# uint32 key -- lookupInTable()'s binary search reads only that much of each
# candidate record off SD before deciding which way to go), followed by a
# blob of NUL-terminated UTF-8 strings that fixed-record fields reference by
# blob-relative uint32 offset. One format, three tables -- see
# sta_gtfs_binary.h for the on-device reader this pairs with.
# Bumped from "STA1" when stop_times/calendar/calendar_dates were added and
# trips.bin grew a serviceIndex in what had been a reserved byte. A firmware
# reading an older "STA1" card still gets correct routes/stops/trips (none of
# those fields changed meaning for an existing reader) but must treat the
# static timetable as unavailable -- that reserved byte reads as service
# index 0 on an old card, which would be a silently wrong answer rather than
# an absent one. sta_gtfs_binary.h's readTableHeader() accepts both and
# reports which, so the firmware can make exactly that distinction.
SD_MAGIC = b"STA2"
SD_MAGIC_LEGACY = b"STA1"
SD_HEADER_STRUCT = struct.Struct("<4sIII")  # magic, recordCount, recordSize, blobOffset

HEADER_NOTE = (
    "// Generated by tools/gen_sta_tables.py from STA's published static GTFS\n"
    "// feed -- do not hand-edit. Re-run the script against a fresh feed to\n"
    "// update (see that script's docstring for where to get one).\n"
)


def load_zip(source: str) -> zipfile.ZipFile:
    if source.startswith("http://") or source.startswith("https://"):
        with urllib.request.urlopen(source, timeout=30) as resp:
            data = resp.read()
        return zipfile.ZipFile(io.BytesIO(data))
    return zipfile.ZipFile(source)


def read_csv(zf: zipfile.ZipFile, name: str):
    with zf.open(name) as f:
        return list(csv.DictReader(io.TextIOWrapper(f, encoding="utf-8-sig")))


def c_string_literal(s: str) -> str:
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def gen_route_table(zf: zipfile.ZipFile) -> None:
    rows = read_csv(zf, "routes.txt")

    # Only rows whose route_id is purely numeric are kept: cross-checked
    # against a live GTFS-RT TripUpdates capture, every trip.route_id seen
    # on the wire was a plain digit string ("1", "28", "294", ...). routes.txt
    # also contains a second family of non-numeric ids ("T 1.", "T 124.", ...)
    # that never appeared in any live trip -- likely a fare/scheduling
    # artifact, not something a TripUpdate will ever reference. Skipping them
    # keeps the table matched to what actually shows up on the wire instead
    # of doubling its size with entries that can never be looked up.
    routes = [r for r in rows if r["route_id"].isdigit()]
    # Sorted by the route_id STRING (not its numeric value): the generated
    # lookupStaRoute() binary-searches with strcmp, which orders "11" before
    # "9" -- sorting numerically here would silently break that binary
    # search's invariant for any pair of ids whose numeric and lexicographic
    # order disagree (nearly all of them).
    routes.sort(key=lambda r: r["route_id"])

    header = INCLUDE_DIR / "sta_route_table.h"
    header.write_text(
        "#pragma once\n\n"
        "// Transit-Elnk-Firmware -- STA route metadata (rider-facing name and\n"
        "// panel color), keyed by the same route_id a live GTFS-RT TripUpdate\n"
        "// carries in its TripDescriptor -- see sta_feed_parser.h. GTFS-RT itself\n"
        "// carries no naming/color data (that's static-GTFS-only), so this is baked\n"
        "// in from STA's routes.txt rather than fetched at runtime.\n" + HEADER_NOTE + "\n"
        "#include <cstddef>\n"
        "#include <cstdint>\n\n"
        "namespace transit {\n"
        "namespace sta {\n\n"
        "struct RouteInfo {\n"
        "  const char* routeId;    // matches TripDescriptor.route_id\n"
        "  const char* shortName;  // rider-facing route number, e.g. \"34\"\n"
        "  uint32_t color;         // 0xRRGGBB, routes.txt route_color\n"
        "  uint32_t textColor;     // 0xRRGGBB, routes.txt route_text_color\n"
        "};\n\n"
        "// Sorted by routeId (numeric order) for lookupStaRoute()'s binary search.\n"
        "extern const RouteInfo kStaRoutes[];\n"
        "extern const size_t kStaRouteCount;\n\n"
        "// nullptr if routeId isn't a route this table knows about (e.g. the feed\n"
        "// added a route since this table was last regenerated) -- callers fall\n"
        "// back to displaying the raw route_id in that case.\n"
        "const RouteInfo* lookupStaRoute(const char* routeId);\n\n"
        "}  // namespace sta\n"
        "}  // namespace transit\n"
    )

    lines = []
    for r in routes:
        lines.append(
            "  {%s, %s, 0x%s, 0x%s},"
            % (
                c_string_literal(r["route_id"]),
                c_string_literal(r["route_short_name"]),
                r["route_color"] or "000000",
                r["route_text_color"] or "FFFFFF",
            )
        )

    src = SRC_DIR / "sta_route_table.cpp"
    src.write_text(
        HEADER_NOTE + "\n"
        '#include "transit/sta_route_table.h"\n\n'
        "#include <cstring>\n\n"
        "namespace transit {\n"
        "namespace sta {\n\n"
        "const RouteInfo kStaRoutes[] = {\n" + "\n".join(lines) + "\n};\n\n"
        "const size_t kStaRouteCount = sizeof(kStaRoutes) / sizeof(kStaRoutes[0]);\n\n"
        "const RouteInfo* lookupStaRoute(const char* routeId) {\n"
        "  size_t lo = 0;\n"
        "  size_t hi = kStaRouteCount;\n"
        "  while (lo < hi) {\n"
        "    size_t mid = lo + (hi - lo) / 2;\n"
        "    int cmp = strcmp(kStaRoutes[mid].routeId, routeId);\n"
        "    if (cmp == 0) return &kStaRoutes[mid];\n"
        "    if (cmp < 0) {\n"
        "      lo = mid + 1;\n"
        "    } else {\n"
        "      hi = mid;\n"
        "    }\n"
        "  }\n"
        "  return nullptr;\n"
        "}\n\n"
        "}  // namespace sta\n"
        "}  // namespace transit\n"
    )
    print(f"wrote {header} and {src} ({len(routes)} routes, "
          f"{len(rows) - len(routes)} non-numeric route_ids skipped)")


def gen_stop_table(zf: zipfile.ZipFile) -> None:
    rows = read_csv(zf, "stops.txt")

    stops = []
    for r in rows:
        code = r["stop_code"].strip()
        stop_id = r["stop_id"].strip()
        if not code.isdigit():
            continue  # a handful of non-revenue/parent-station rows lack a real code
        if len(stop_id) > 8:
            raise ValueError(f"stop_id {stop_id!r} exceeds the 8-char fixed field")
        stops.append((int(code), stop_id, r["stop_name"].strip()))
    stops.sort(key=lambda s: s[0])

    dupes = [c for i, (c, *_r) in enumerate(stops) if i > 0 and c == stops[i - 1][0]]
    if dupes:
        raise ValueError(f"duplicate stop_code values, lookupStaStop()'s binary search "
                          f"needs unique keys: {dupes}")

    header = INCLUDE_DIR / "sta_stop_table.h"
    header.write_text(
        "#pragma once\n\n"
        "// Transit-Elnk-Firmware -- STA stop lookup, keyed by the numeric stop code\n"
        "// printed on the physical stop sign (what ConfigStore::staStopCode() stores,\n"
        "// entered during setup -- see setup_flow.h). Resolves that to the\n"
        "// alphanumeric stop_id the GTFS-RT feed actually keys its\n"
        "// stop_time_update entries on (see sta_feed_parser.h), plus a human-readable\n"
        "// name to confirm the pick during setup. Neither the code->id mapping nor the\n"
        "// name is carried in the live feed itself -- both are static-GTFS-only, so\n"
        "// this is baked in from STA's stops.txt rather than fetched at runtime.\n" + HEADER_NOTE + "\n"
        "#include <cstddef>\n"
        "#include <cstdint>\n\n"
        "namespace transit {\n"
        "namespace sta {\n\n"
        "struct StopInfo {\n"
        "  uint16_t stopCode;   // printed on the sign; ConfigStore::staStopCode()\n"
        "  char stopId[9];      // GTFS-RT stop_time_update.stop_id (<=8 chars + NUL)\n"
        "  const char* stopName;\n"
        "};\n\n"
        "// Sorted by stopCode for lookupStaStop()'s binary search.\n"
        "extern const StopInfo kStaStops[];\n"
        "extern const size_t kStaStopCount;\n\n"
        "// nullptr if stopCode isn't in this table (a typo, or STA added a stop since\n"
        "// this table was last regenerated) -- callers surface that as \"stop not\n"
        "// found\" rather than silently fetching nothing.\n"
        "const StopInfo* lookupStaStop(uint16_t stopCode);\n\n"
        "}  // namespace sta\n"
        "}  // namespace transit\n"
    )

    lines = []
    for code, stop_id, name in stops:
        lines.append(
            "  {%du, %s, %s}," % (code, c_string_literal(stop_id), c_string_literal(name))
        )

    src = SRC_DIR / "sta_stop_table.cpp"
    src.write_text(
        HEADER_NOTE + "\n"
        '#include "transit/sta_stop_table.h"\n\n'
        "namespace transit {\n"
        "namespace sta {\n\n"
        "const StopInfo kStaStops[] = {\n" + "\n".join(lines) + "\n};\n\n"
        "const size_t kStaStopCount = sizeof(kStaStops) / sizeof(kStaStops[0]);\n\n"
        "const StopInfo* lookupStaStop(uint16_t stopCode) {\n"
        "  size_t lo = 0;\n"
        "  size_t hi = kStaStopCount;\n"
        "  while (lo < hi) {\n"
        "    size_t mid = lo + (hi - lo) / 2;\n"
        "    if (kStaStops[mid].stopCode == stopCode) return &kStaStops[mid];\n"
        "    if (kStaStops[mid].stopCode < stopCode) {\n"
        "      lo = mid + 1;\n"
        "    } else {\n"
        "      hi = mid;\n"
        "    }\n"
        "  }\n"
        "  return nullptr;\n"
        "}\n\n"
        "}  // namespace sta\n"
        "}  // namespace transit\n"
    )
    print(f"wrote {header} and {src} ({len(stops)} stops, "
          f"{len(rows) - len(stops)} rows without a numeric stop_code skipped)")


def write_indexed_table(path: Path, records: list, blob_parts: list) -> None:
    """records: list of (key:int, packed_fixed_bytes_minus_key:bytes) already
    sorted ascending by key. blob_parts: list of bytes to concatenate (each
    already NUL-terminated) -- callers built each record's *Offset fields as
    indexes into this same list's eventual concatenation, computed by
    intern_blob_string() below.
    """
    if not records:
        raise ValueError(f"no records for {path}")
    # blob_parts is empty for the purely-numeric tables (stop_times,
    # calendar, calendar_dates) -- they carry no text of their own, since
    # every string a scheduled departure needs is already in trips.bin or
    # routes.bin and is reached by id.
    key_struct = struct.Struct("<I")
    record_size = 4 + len(records[0][1])
    body = b"".join(key_struct.pack(key) + rest for key, rest in records)
    blob = b"".join(blob_parts)
    blob_offset = SD_HEADER_STRUCT.size + len(body)
    header = SD_HEADER_STRUCT.pack(SD_MAGIC, len(records), record_size, blob_offset)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(header + body + blob)


class BlobBuilder:
    """Accumulates NUL-terminated strings, handing back each one's
    blob-relative byte offset -- interning so a repeated string (e.g. the
    same headsign shared by many trips) is stored once."""

    def __init__(self):
        self.parts: list[bytes] = []
        self.offsets: dict = {}
        self.size = 0

    def intern(self, s: str) -> int:
        if s in self.offsets:
            return self.offsets[s]
        offset = self.size
        encoded = s.encode("utf-8") + b"\0"
        self.parts.append(encoded)
        self.offsets[s] = offset
        self.size += len(encoded)
        return offset


def gen_schedule_binaries(zf: zipfile.ZipFile, trips: list, service_index: dict) -> None:
    """sd_card_data/sta/{stop_times,calendar,calendar_dates}.bin -- the static
    timetable itself, so the board can show scheduled departures with no
    network at all. See docs/OFFLINE_AND_BUS_WIFI.md and sta_gtfs_binary.h.

    These are much bigger than the other tables (stop_times is ~2.7MB against
    a few hundred KB for the rest) but they are the only ones that answer
    "when is the next bus" rather than "what is this thing called", which is
    what makes an offline board useful rather than merely non-blank.
    """
    stop_code_for_id = {}
    for r in read_csv(zf, "stops.txt"):
        code = r["stop_code"].strip()
        if code.isdigit():
            stop_code_for_id[r["stop_id"].strip()] = int(code)

    known_trip_ids = {int(r["trip_id"]) for r in trips}

    def to_seconds(hhmmss: str) -> int:
        """GTFS times run past 24:00:00 for trips that begin before midnight
        and end after it -- STA's feed reaches 25:10:00. They are measured
        from noon-minus-12h of the service day, NOT from midnight; see
        include/transit/local_time.h for why that distinction matters on the
        two DST days a year."""
        h, m, sec = (int(x) for x in hhmmss.split(":"))
        return h * 3600 + m * 60 + sec

    # --- stop_times.bin: stopCode(u32) -> tripId(u32), departureSec(u32)
    #
    # Unlike every other table here, this one holds MANY records per key --
    # the lookup is a lower-bound search to the first record for a stop, then
    # a forward scan while the key still matches. Sorting by (stopCode,
    # departureSec) is what makes that scan come out in departure order, so
    # the reader stops at the first match after "now" instead of reading the
    # whole block.
    skipped = 0
    rows = []
    for r in read_csv(zf, "stop_times.txt"):
        stop_code = stop_code_for_id.get(r["stop_id"].strip())
        trip_id = r["trip_id"].strip()
        departure = r["departure_time"].strip()
        # A stop with no numeric stop_code can't be addressed from a physical
        # stop sign, an unknown trip can't be resolved against trips.bin, and
        # a blank departure_time is a non-timepoint row with nothing to show.
        if stop_code is None or not trip_id.isdigit() or int(trip_id) not in known_trip_ids or not departure:
            skipped += 1
            continue
        rows.append((stop_code, to_seconds(departure), int(trip_id)))

    rows.sort()  # by stopCode, then departureSec, then tripId
    records = [(stop_code, struct.pack("<II", trip_id, dep)) for stop_code, dep, trip_id in rows]
    write_indexed_table(SD_DATA_DIR / "stop_times.bin", records, [])

    # --- calendar.bin: serviceIndex(u32) -> daysMask(u8)+3 reserved,
    # startDate(u32 as YYYYMMDD), endDate(u32)
    #
    # daysMask is indexed by struct tm's tm_wday (bit 0 = Sunday), not by
    # calendar.txt's own column order (which starts at Monday) -- the
    # firmware has a tm_wday in hand and no reason to renumber it.
    weekday_columns = ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"]
    cal_records = []
    for r in read_csv(zf, "calendar.txt"):
        idx = service_index.get(r["service_id"])
        if idx is None:
            continue  # a service no trip references is dead weight
        mask = 0
        for bit, column in enumerate(weekday_columns):
            if r[column].strip() == "1":
                mask |= 1 << bit
        cal_records.append((idx, struct.pack("<B3xII", mask, int(r["start_date"]), int(r["end_date"]))))
    cal_records.sort()
    write_indexed_table(SD_DATA_DIR / "calendar.bin", cal_records, [])

    # --- calendar_dates.bin: date(u32 YYYYMMDD) -> serviceIndex(u8),
    # exceptionType(u8: 1 = added, 2 = removed), 2 reserved
    #
    # Keyed on the date, not the service, because the question the firmware
    # asks is "what exceptions apply today" -- one lower-bound search per
    # wake instead of one per service. Holiday schedules live here, and
    # ignoring them would show a full weekday timetable on Thanksgiving.
    exception_records = []
    for r in read_csv(zf, "calendar_dates.txt"):
        idx = service_index.get(r["service_id"])
        if idx is None:
            continue
        exception_records.append((int(r["date"]), struct.pack("<BB2x", idx, int(r["exception_type"]))))
    exception_records.sort()
    # calendar_dates.txt is genuinely optional -- a feed with no holiday
    # exceptions has nothing to write, and sta_static_schedule.h already
    # treats a missing file as "no exceptions" rather than an error. Raising
    # here would abort the run after stop_times.bin and calendar.bin were
    # already written, leaving a half-generated card. A stale file from a
    # previous feed is removed so it can't outlive the data it came from.
    exceptions_path = SD_DATA_DIR / "calendar_dates.bin"
    if exception_records:
        write_indexed_table(exceptions_path, exception_records, [])
    elif exceptions_path.exists():
        exceptions_path.unlink()

    validity = [(int(r["start_date"]), int(r["end_date"])) for r in read_csv(zf, "calendar.txt")]
    window = f"{min(v[0] for v in validity)}..{max(v[1] for v in validity)}" if validity else "unknown"
    size_mb = (SD_DATA_DIR / "stop_times.bin").stat().st_size / 1024 / 1024
    print(f"wrote {SD_DATA_DIR}/{{stop_times,calendar,calendar_dates}}.bin "
          f"({len(records):,} stop_times rows in {size_mb:.2f} MB, {len(cal_records)} services, "
          f"{len(exception_records)} date exceptions, valid {window}, {skipped:,} rows skipped)")


def gen_sd_binaries(zf: zipfile.ZipFile) -> None:
    """sd_card_data/sta/{routes,stops,trips}.bin -- see this script's module
    docstring for why these exist alongside (not instead of) the baked-in
    flash tables, and sta_gtfs_binary.h for the shared record format."""
    routes = [r for r in read_csv(zf, "routes.txt") if r["route_id"].isdigit()]
    stops = [r for r in read_csv(zf, "stops.txt") if r["stop_code"].strip().isdigit()]
    trips = [r for r in read_csv(zf, "trips.txt") if r["trip_id"].isdigit() and r["route_id"].isdigit()]

    # --- routes.bin: routeId(u32) -> shortNameOffset(u32), color(u32), textColor(u32)
    blob = BlobBuilder()
    records = []
    for r in sorted(routes, key=lambda r: int(r["route_id"])):
        name_off = blob.intern(r["route_short_name"].strip())
        color = int(r["route_color"] or "000000", 16)
        text_color = int(r["route_text_color"] or "FFFFFF", 16)
        records.append((int(r["route_id"]), struct.pack("<III", name_off, color, text_color)))
    write_indexed_table(SD_DATA_DIR / "routes.bin", records, blob.parts)

    # --- stops.bin: stopCode(u32) -> stopId(8 bytes, not NUL-padded -- always
    # exactly 8 per tools/gen_sta_tables.py's stop_id length check below),
    # nameOffset(u32), lat(f32), lon(f32)
    blob = BlobBuilder()
    records = []
    for r in sorted(stops, key=lambda r: int(r["stop_code"])):
        stop_id = r["stop_id"].strip()
        if len(stop_id) > 8:
            raise ValueError(f"stop_id {stop_id!r} exceeds the 8-byte fixed field")
        stop_id_bytes = stop_id.encode("ascii").ljust(8, b"\0")
        name_off = blob.intern(r["stop_name"].strip())
        records.append((
            int(r["stop_code"]),
            stop_id_bytes + struct.pack("<Iff", name_off, float(r["stop_lat"]), float(r["stop_lon"])),
        ))
    write_indexed_table(SD_DATA_DIR / "stops.bin", records, blob.parts)

    # --- trips.bin: tripId(u32) -> routeId(u32), directionId(u8),
    # serviceIndex(u8), 2 reserved, headsignOffset(u32)
    #
    # service_id is a string in STA's feed ("671.0.1", not a number), so it
    # can't be stored or keyed on directly. Each distinct value gets an
    # index instead, assigned here and shared with calendar.bin /
    # calendar_dates.bin below. It fits in a u8 because the feed has 24 of
    # them; the assert keeps that from becoming a silent truncation if STA
    # ever restructures its calendar.
    service_ids = sorted({r["service_id"] for r in trips})
    if len(service_ids) > 255:
        raise ValueError(f"{len(service_ids)} service_ids exceeds the u8 serviceIndex field")
    service_index = {sid: i for i, sid in enumerate(service_ids)}

    blob = BlobBuilder()
    records = []
    for r in sorted(trips, key=lambda r: int(r["trip_id"])):
        headsign_off = blob.intern(r["trip_headsign"].strip())
        direction_id = int(r["direction_id"]) if r["direction_id"] in ("0", "1") else 0
        records.append((
            int(r["trip_id"]),
            struct.pack("<IBB2xI", int(r["route_id"]), direction_id,
                        service_index[r["service_id"]], headsign_off),
        ))
    write_indexed_table(SD_DATA_DIR / "trips.bin", records, blob.parts)

    gen_schedule_binaries(zf, trips, service_index)

    readme = SD_DATA_DIR.parent / "README.md"
    readme.write_text(
        "# STA reference data for the SD card\n\n"
        "Generated by tools/gen_sta_tables.py -- copy this sta/ directory onto\n"
        "the board's SD card (path /sta/*.bin) to supplement\n"
        "the small always-available flash tables with STA's full static GTFS\n"
        "data: real per-trip headsigns and reliable direction grouping (trips.bin),\n"
        "plus stop lat/lon for future nearby-stop search (stops.bin). Optional --\n"
        "the firmware works without a card or without these files present, just\n"
        "with less trip detail. See docs/STA_INTEGRATION.md.\n"
    )
    print(f"wrote {SD_DATA_DIR}/{{routes,stops,trips}}.bin "
          f"({len(routes)} routes, {len(stops)} stops, {len(trips)} trips) and {readme}")


def main() -> None:
    if len(sys.argv) != 2:
        print(__doc__)
        sys.exit(1)
    zf = load_zip(sys.argv[1])
    gen_route_table(zf)
    gen_stop_table(zf)
    gen_sd_binaries(zf)


if __name__ == "__main__":
    main()
