#!/usr/bin/env python3
"""Regenerate include/transit/sta_route_table.h(.cpp) and
sta_stop_table.h(.cpp) from Spokane Transit Authority's published static
GTFS feed.

STA's own site (spokanetransit.com) sits behind Cloudflare bot protection
that blocks a plain HTTP client (including this device's firmware), so this
reads from the Mobility Database's public unauthenticated mirror instead:
https://storage.googleapis.com/storage/v1/b/mdb-latest/o?prefix=us-washington-spokane-transit-authority
Look up the current .zip object there (the generation/filename changes each
time Mobility Database re-crawls STA) and pass its download URL or a local
path to this script.

The firmware bakes these tables in at build time rather than fetching STA's
static GTFS at runtime: it's a large (~2MB zipped), slow-changing dataset
(STA doesn't add/remove stops or renumber routes often) that only exists to
resolve two things the live GTFS-RT feed doesn't carry itself --
    1. route_id -> rider-facing route number/name/color (routes.txt)
    2. the numeric stop code printed on a physical stop sign -> the
       alphanumeric internal stop_id the GTFS-RT feed actually keys on, plus
       a human-readable stop name to confirm the pick during setup
       (stops.txt)
-- both of which are effectively static reference data, not something worth
a live fetch (or the RAM/flash to cache) on every wake cycle.

Usage:
    python3 tools/gen_sta_tables.py path/to/sta_gtfs.zip
    python3 tools/gen_sta_tables.py https://storage.googleapis.com/.../sta-gtfs-NNN.zip

Regenerate periodically (STA route/stop changes are infrequent enough that
this doesn't need to run on every build) and commit the resulting header/cpp
pairs like any other generated asset in this repo (see
include/transit/powered_by_transit_badge.h for the same pattern).
"""

import csv
import io
import sys
import urllib.request
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INCLUDE_DIR = REPO_ROOT / "include" / "transit"
SRC_DIR = REPO_ROOT / "src" / "transit"

HEADER_NOTE = (
    "// Generated by tools/gen_sta_tables.py from STA's published static GTFS\n"
    "// feed -- do not hand-edit. Re-run the script against a fresh feed to\n"
    "// update (see that script's docstring for where to get one).\n"
)


def load_zip(source: str) -> zipfile.ZipFile:
    if source.startswith("http://") or source.startswith("https://"):
        with urllib.request.urlopen(source, timeout=30) as resp:
            data = resp.read()
        return zipfile.ZipFile(io.BytesIO(data))
    return zipfile.ZipFile(source)


def read_csv(zf: zipfile.ZipFile, name: str):
    with zf.open(name) as f:
        return list(csv.DictReader(io.TextIOWrapper(f, encoding="utf-8-sig")))


def c_string_literal(s: str) -> str:
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def gen_route_table(zf: zipfile.ZipFile) -> None:
    rows = read_csv(zf, "routes.txt")

    # Only rows whose route_id is purely numeric are kept: cross-checked
    # against a live GTFS-RT TripUpdates capture, every trip.route_id seen
    # on the wire was a plain digit string ("1", "28", "294", ...). routes.txt
    # also contains a second family of non-numeric ids ("T 1.", "T 124.", ...)
    # that never appeared in any live trip -- likely a fare/scheduling
    # artifact, not something a TripUpdate will ever reference. Skipping them
    # keeps the table matched to what actually shows up on the wire instead
    # of doubling its size with entries that can never be looked up.
    routes = [r for r in rows if r["route_id"].isdigit()]
    # Sorted by the route_id STRING (not its numeric value): the generated
    # lookupStaRoute() binary-searches with strcmp, which orders "11" before
    # "9" -- sorting numerically here would silently break that binary
    # search's invariant for any pair of ids whose numeric and lexicographic
    # order disagree (nearly all of them).
    routes.sort(key=lambda r: r["route_id"])

    header = INCLUDE_DIR / "sta_route_table.h"
    header.write_text(
        "#pragma once\n\n"
        "// Transit-Elnk-Firmware -- STA route metadata (rider-facing name and\n"
        "// panel color), keyed by the same route_id a live GTFS-RT TripUpdate\n"
        "// carries in its TripDescriptor -- see sta_feed_parser.h. GTFS-RT itself\n"
        "// carries no naming/color data (that's static-GTFS-only), so this is baked\n"
        "// in from STA's routes.txt rather than fetched at runtime.\n" + HEADER_NOTE + "\n"
        "#include <cstddef>\n"
        "#include <cstdint>\n\n"
        "namespace transit {\n"
        "namespace sta {\n\n"
        "struct RouteInfo {\n"
        "  const char* routeId;    // matches TripDescriptor.route_id\n"
        "  const char* shortName;  // rider-facing route number, e.g. \"34\"\n"
        "  uint32_t color;         // 0xRRGGBB, routes.txt route_color\n"
        "  uint32_t textColor;     // 0xRRGGBB, routes.txt route_text_color\n"
        "};\n\n"
        "// Sorted by routeId (numeric order) for lookupStaRoute()'s binary search.\n"
        "extern const RouteInfo kStaRoutes[];\n"
        "extern const size_t kStaRouteCount;\n\n"
        "// nullptr if routeId isn't a route this table knows about (e.g. the feed\n"
        "// added a route since this table was last regenerated) -- callers fall\n"
        "// back to displaying the raw route_id in that case.\n"
        "const RouteInfo* lookupStaRoute(const char* routeId);\n\n"
        "}  // namespace sta\n"
        "}  // namespace transit\n"
    )

    lines = []
    for r in routes:
        lines.append(
            "  {%s, %s, 0x%s, 0x%s},"
            % (
                c_string_literal(r["route_id"]),
                c_string_literal(r["route_short_name"]),
                r["route_color"] or "000000",
                r["route_text_color"] or "FFFFFF",
            )
        )

    src = SRC_DIR / "sta_route_table.cpp"
    src.write_text(
        HEADER_NOTE + "\n"
        '#include "transit/sta_route_table.h"\n\n'
        "#include <cstring>\n\n"
        "namespace transit {\n"
        "namespace sta {\n\n"
        "const RouteInfo kStaRoutes[] = {\n" + "\n".join(lines) + "\n};\n\n"
        "const size_t kStaRouteCount = sizeof(kStaRoutes) / sizeof(kStaRoutes[0]);\n\n"
        "const RouteInfo* lookupStaRoute(const char* routeId) {\n"
        "  size_t lo = 0;\n"
        "  size_t hi = kStaRouteCount;\n"
        "  while (lo < hi) {\n"
        "    size_t mid = lo + (hi - lo) / 2;\n"
        "    int cmp = strcmp(kStaRoutes[mid].routeId, routeId);\n"
        "    if (cmp == 0) return &kStaRoutes[mid];\n"
        "    if (cmp < 0) {\n"
        "      lo = mid + 1;\n"
        "    } else {\n"
        "      hi = mid;\n"
        "    }\n"
        "  }\n"
        "  return nullptr;\n"
        "}\n\n"
        "}  // namespace sta\n"
        "}  // namespace transit\n"
    )
    print(f"wrote {header} and {src} ({len(routes)} routes, "
          f"{len(rows) - len(routes)} non-numeric route_ids skipped)")


def gen_stop_table(zf: zipfile.ZipFile) -> None:
    rows = read_csv(zf, "stops.txt")

    stops = []
    for r in rows:
        code = r["stop_code"].strip()
        stop_id = r["stop_id"].strip()
        if not code.isdigit():
            continue  # a handful of non-revenue/parent-station rows lack a real code
        if len(stop_id) > 8:
            raise ValueError(f"stop_id {stop_id!r} exceeds the 8-char fixed field")
        stops.append((int(code), stop_id, r["stop_name"].strip()))
    stops.sort(key=lambda s: s[0])

    dupes = [c for i, (c, *_r) in enumerate(stops) if i > 0 and c == stops[i - 1][0]]
    if dupes:
        raise ValueError(f"duplicate stop_code values, lookupStaStop()'s binary search "
                          f"needs unique keys: {dupes}")

    header = INCLUDE_DIR / "sta_stop_table.h"
    header.write_text(
        "#pragma once\n\n"
        "// Transit-Elnk-Firmware -- STA stop lookup, keyed by the numeric stop code\n"
        "// printed on the physical stop sign (what ConfigStore::staStopCode() stores,\n"
        "// entered during setup -- see setup_flow.h). Resolves that to the\n"
        "// alphanumeric stop_id the GTFS-RT feed actually keys its\n"
        "// stop_time_update entries on (see sta_feed_parser.h), plus a human-readable\n"
        "// name to confirm the pick during setup. Neither the code->id mapping nor the\n"
        "// name is carried in the live feed itself -- both are static-GTFS-only, so\n"
        "// this is baked in from STA's stops.txt rather than fetched at runtime.\n" + HEADER_NOTE + "\n"
        "#include <cstddef>\n"
        "#include <cstdint>\n\n"
        "namespace transit {\n"
        "namespace sta {\n\n"
        "struct StopInfo {\n"
        "  uint16_t stopCode;   // printed on the sign; ConfigStore::staStopCode()\n"
        "  char stopId[9];      // GTFS-RT stop_time_update.stop_id (<=8 chars + NUL)\n"
        "  const char* stopName;\n"
        "};\n\n"
        "// Sorted by stopCode for lookupStaStop()'s binary search.\n"
        "extern const StopInfo kStaStops[];\n"
        "extern const size_t kStaStopCount;\n\n"
        "// nullptr if stopCode isn't in this table (a typo, or STA added a stop since\n"
        "// this table was last regenerated) -- callers surface that as \"stop not\n"
        "// found\" rather than silently fetching nothing.\n"
        "const StopInfo* lookupStaStop(uint16_t stopCode);\n\n"
        "}  // namespace sta\n"
        "}  // namespace transit\n"
    )

    lines = []
    for code, stop_id, name in stops:
        lines.append(
            "  {%du, %s, %s}," % (code, c_string_literal(stop_id), c_string_literal(name))
        )

    src = SRC_DIR / "sta_stop_table.cpp"
    src.write_text(
        HEADER_NOTE + "\n"
        '#include "transit/sta_stop_table.h"\n\n'
        "namespace transit {\n"
        "namespace sta {\n\n"
        "const StopInfo kStaStops[] = {\n" + "\n".join(lines) + "\n};\n\n"
        "const size_t kStaStopCount = sizeof(kStaStops) / sizeof(kStaStops[0]);\n\n"
        "const StopInfo* lookupStaStop(uint16_t stopCode) {\n"
        "  size_t lo = 0;\n"
        "  size_t hi = kStaStopCount;\n"
        "  while (lo < hi) {\n"
        "    size_t mid = lo + (hi - lo) / 2;\n"
        "    if (kStaStops[mid].stopCode == stopCode) return &kStaStops[mid];\n"
        "    if (kStaStops[mid].stopCode < stopCode) {\n"
        "      lo = mid + 1;\n"
        "    } else {\n"
        "      hi = mid;\n"
        "    }\n"
        "  }\n"
        "  return nullptr;\n"
        "}\n\n"
        "}  // namespace sta\n"
        "}  // namespace transit\n"
    )
    print(f"wrote {header} and {src} ({len(stops)} stops, "
          f"{len(rows) - len(stops)} rows without a numeric stop_code skipped)")


def main() -> None:
    if len(sys.argv) != 2:
        print(__doc__)
        sys.exit(1)
    zf = load_zip(sys.argv[1])
    gen_route_table(zf)
    gen_stop_table(zf)


if __name__ == "__main__":
    main()
